import { KINDS, CAP, RECOVERY, fresh, restore, recover, requirements, supply, nextSlot, canMerge, drop, upgrade, undo, returnPart, type Part, type ProgressEvent } from './merge-placement-state';
import './merge-placement.css';
export const KEY='dbg-lab-merge-placement-e-v1';
const NONE=-1, icons=['△','◉','⚙','┬'];
const partHTML=(p:Part)=>`<b>${icons[p.kind]}</b><span>${KINDS[p.kind]}</span><small>Lv.${p.level}</small>`;
export function startMergePlacement(parent:string) {
  const root=document.getElementById(parent)!;let storageOK=true,raw:string|null=null;
  try{raw=localStorage.getItem(KEY);}catch{storageOK=false;}
  let s=restore(raw),selected=NONE,message='점선 칸이 다음 입고 위치예요. 맞닿은 같은 부품 2개를 겹쳐 조립하세요.';
  let accelerated=false,ticks=0,blockClickUntil=0,pointer:{index:number;id:number;x:number;y:number;dragging:boolean}|null=null,ghost:HTMLElement|null=null;
  const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(s));}catch{storageOK=false;}};
  function bike(){const [frame,wheels,drive,bar]=s.installed;return `<svg viewBox="0 0 260 105" aria-label="고객 자전거 조립 ${s.installed.filter(Boolean).length}/4" role="img"><g fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="5"><g stroke="${wheels?'#425d53':'#d7d8d1'}"><circle cx="60" cy="70" r="28"/><circle cx="200" cy="70" r="28"/></g><path stroke="${frame?'#c77432':'#d7d8d1'}" d="M60 70L99 25L125 70L60 70M99 25L183 25L125 70M183 25L200 70M99 25L94 15M85 15H105"/><g stroke="${drive?'#425d53':'#d7d8d1'}"><circle cx="125" cy="70" r="9"/><path d="M125 70L139 80L147 80"/></g><path stroke="${bar?'#425d53':'#d7d8d1'}" d="M183 25L178 10H202L207 17"/></g></svg>`;}
  function render(){
    const req=requirements(s),scheduled=nextSlot(s),detailsOpen=root.querySelector('details')?.open??false;
    root.innerHTML=`<section class="placement-game" aria-label="예정 배치·인접 머지 E안">
      <header><strong>자전거 가게 · 작업대 정리</strong><span>급여 ${s.coins} C</span></header>
      <div class="placement-energy"><b data-energy></b><span data-clock></span></div>
      <div class="placement-order"><b>고객 주문 ${s.order+1} · ${['통학 자전거','시티 자전거','주말 자전거'][s.order%3]}</b>${bike()}<div class="placement-slots">${KINDS.map((k,i)=>`<span data-install-slot="${i}" class="${s.installed[i]?'done':''}">${icons[i]} ${k}<br>${s.installed[i]?'장착 완료':`Lv.${req[i]} 필요`}</span>`).join('')}</div></div>
      <p class="placement-rule">예정 칸 자동 입고 · 이동 불가 · 상하좌우 2개 합성 · 완성 즉시 장착/납품</p>
      <div class="placement-workbench"><div class="placement-board" role="group" aria-label="6열 7행 작업대">${s.board.map((part,i)=>`<button data-cell="${i}" class="placement-cell ${part?`kind-${part.kind}`:''} ${selected===i?'selected':''} ${canMerge(s,selected,i)?'merge-target':''} ${scheduled===i?'next-slot':''}" aria-pressed="${selected===i}" aria-label="${Math.floor(i/6)+1}행 ${i%6+1}열 ${part?`${KINDS[part.kind]} 레벨 ${part.level}`:scheduled===i?'다음 입고 예정 빈칸':'빈칸'}">${part?partHTML(part):scheduled===i?'<small>다음<br>입고</small>':''}</button>`).join('')}</div>
        <div class="placement-mini-actions" aria-label="보조 조작"><button data-action="undo" ${s.undo?'':'disabled'} title="직전 합성 또는 반품 되돌리기" aria-label="직전 행동 되돌리기">↶</button><button data-action="return" ${selected>=0&&s.board[selected]?'':'disabled'} title="선택 부품 반품" aria-label="선택 부품 반품">↗</button></div></div>
      <button class="placement-supply" data-action="supply"><b>📦 부품 상자 열기</b><small>예정 칸에 자동 배치 · 체력 −1</small></button>
      <p class="placement-message" role="status">${message}</p>
      <footer>내 드림 바이크 ${'★'.repeat(s.growth)}${'☆'.repeat(3-s.growth)} · 빈칸 ${s.board.filter(p=>!p).length}/42 <button data-action="upgrade" ${s.growth>=3||s.coins<500?'disabled':''}>성장</button></footer>
      <details ${detailsOpen?'open':''}><summary>조작 안내 · 랩 테스트 도구</summary><p>점선으로 표시된 예정 칸은 보드 아래 중앙에서 가까운 빈칸부터 정해집니다. 상자를 열면 추첨된 부품이 그 칸에 바로 들어갑니다. 놓인 부품은 빈칸으로 옮길 수 없고, 같은 종류·레벨의 상하좌우 이웃에게 겹칠 때만 합쳐집니다.</p><p>주문 레벨을 충족한 부품은 즉시 자전거에 장착되고, 네 부품이 모이면 자동 납품되어 500 C를 받습니다. 한 행동에서 한 주문만 납품합니다. 되돌리기는 최근 합성·반품·성장 1회에 적용되며 새 상자를 열면 지워집니다.</p><p>체력 30, 상자당 1, 실제 10분당 1 회복. Lv.1 80% / Lv.2 20%. 미장착 종류 70% 우선 및 4회 미출현 보장 수치는 비교용입니다.</p><button data-action="charge">테스트: 체력 충전</button><button data-action="speed">테스트: 10초 회복 ${accelerated?'ON':'OFF'}</button><button data-action="reset">E안 저장 초기화</button><p>공급 ${s.supplied} · 합성 ${s.merges} · 반품 ${s.returned} · 납품 ${s.order}</p></details><small data-save>${storageOK?'E안 자동 저장 · 기존 진행 이전 지원':'저장 불가: 이 화면에서만 진행됩니다.'}</small>
    </section>`;updateClock();
  }
  function updateClock(){const remaining=Math.max(0,Math.ceil((RECOVERY-(Date.now()-s.anchor))/1000)),clock=root.querySelector('[data-clock]'),energy=root.querySelector('[data-energy]'),btn=root.querySelector<HTMLButtonElement>('[data-action=supply]');if(clock)clock.textContent=s.energy===CAP?'충전 완료':accelerated?'랩: 10초마다 +1':`다음 +1 ${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;if(energy)energy.textContent=`⚡ 알바 체력 ${s.energy}/${CAP}`;if(btn){const full=nextSlot(s)<0;btn.disabled=s.energy<1||full;btn.querySelector('small')!.textContent=full?'작업대 공간 확보 필요':s.energy<1?'체력 회복 중':'예정 칸에 자동 배치 · 체력 −1';}}
  function play(events:ProgressEvent[]){for(const event of events){root.dispatchEvent(new CustomEvent('dbg:merge-motion',{detail:event,bubbles:true}));const target=event.type==='installed'?root.querySelector(`[data-install-slot="${event.kind}"]`):event.type==='delivered'?root.querySelector('.placement-order'):event.type==='placed'||event.type==='merged'?root.querySelector(`[data-cell="${event.type==='placed'?event.index:event.to}"]`):null;target?.classList.add(`motion-${event.type}`);if(target)setTimeout(()=>target.classList.remove(`motion-${event.type}`),550);}const installed=events.filter(e=>e.type==='installed').length,delivered=events.some(e=>e.type==='delivered');message=delivered?'자전거가 완성되어 자동 납품했어요! 급여 500 C를 받았습니다.':installed?`완성 부품 ${installed}개를 자전거에 자동 장착했어요.`:events.some(e=>e.type==='placed')?'예정 칸에 부품이 들어왔어요. 인접한 같은 부품과 합쳐 보세요.':'인접한 두 부품을 합쳤어요.';}
  function act(result:{events:ProgressEvent[]}|null){if(!result)return;selected=NONE;save();render();play(result.events);}
  const click=(e:Event)=>{if(pointer?.dragging||(performance.now()<blockClickUntil&&(e as MouseEvent).detail!==0))return;const target=(e.target as Element).closest<HTMLButtonElement>('button');if(!target||target.disabled)return;if(target.dataset.cell!==undefined){const i=Number(target.dataset.cell);if(selected===i)selected=NONE;else if(selected>=0&&canMerge(s,selected,i)){act(drop(s,selected,i));return;}else if(s.board[i]){selected=i;message='같은 종류·레벨의 상하좌우 부품에 겹치면 합쳐집니다.';}else{selected=NONE;message='부품은 빈칸으로 이동할 수 없어요.';}}else switch(target.dataset.action){case'supply':act(supply(s));return;case'undo':if(undo(s)){selected=NONE;message='직전 행동을 한 칸 되돌렸어요.';}break;case'return':if(s.board[selected]&&window.confirm('선택한 부품을 반품할까요? 체력은 반환되지 않습니다.')){returnPart(s,selected);selected=NONE;message='부품을 반품했어요. 작은 되돌리기 버튼으로 복구할 수 있습니다.';}break;case'upgrade':if(upgrade(s))message='급여로 내 드림 바이크를 성장시켰어요!';break;case'charge':s.energy=CAP;s.anchor=Date.now();message='테스트용 체력을 충전했어요.';break;case'speed':accelerated=!accelerated;ticks=0;break;case'reset':if(window.confirm('E안의 진행을 초기화할까요?')){s=fresh();selected=NONE;message='E안 첫 주문을 시작합니다.';}break;}save();render();};
  function clearDrag(){const id=pointer?.id;pointer=null;if(id!==undefined&&root.hasPointerCapture?.(id))root.releasePointerCapture(id);ghost?.remove();ghost=null;root.querySelectorAll('.drop-merge,.drop-invalid,.drag-source').forEach(el=>el.classList.remove('drop-merge','drop-invalid','drag-source'));}
  const down=(e:PointerEvent)=>{if(pointer||e.isPrimary===false||e.button!==0)return;const el=(e.target as Element).closest<HTMLElement>('[data-cell]');if(!el)return;const index=Number(el.dataset.cell);if(s.board[index])pointer={index,id:e.pointerId,x:e.clientX,y:e.clientY,dragging:false};};
  const drag=(e:PointerEvent)=>{if(!pointer||pointer.id!==e.pointerId)return;if(!pointer.dragging&&Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)<8)return;e.preventDefault();if(!pointer.dragging){pointer.dragging=true;root.setPointerCapture(e.pointerId);const source=root.querySelector<HTMLElement>(`[data-cell="${pointer.index}"]`)!;ghost=document.createElement('div');ghost.className='placement-drag-ghost';ghost.innerHTML=partHTML(s.board[pointer.index]!);document.body.append(ghost);source.classList.add('drag-source');}ghost!.style.left=`${e.clientX}px`;ghost!.style.top=`${e.clientY-18}px`;root.querySelectorAll('.drop-merge,.drop-invalid').forEach(el=>el.classList.remove('drop-merge','drop-invalid'));const cell=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-cell]');if(cell&&root.contains(cell))cell.classList.add(canMerge(s,pointer.index,Number(cell.dataset.cell))?'drop-merge':'drop-invalid');};
  const up=(e:PointerEvent)=>{if(!pointer||pointer.id!==e.pointerId)return;const from=pointer,cell=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-cell]');clearDrag();if(!from.dragging)return;blockClickUntil=performance.now()+500;if(cell&&root.contains(cell)&&canMerge(s,from.index,Number(cell.dataset.cell)))act(drop(s,from.index,Number(cell.dataset.cell)));else{selected=from.index;message='이동은 불가해요. 인접한 같은 부품에만 겹쳐 주세요.';save();render();}};
  const cancel=()=>{if(pointer?.dragging)blockClickUntil=performance.now()+500;clearDrag();};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){cancel();selected=NONE;message='선택을 취소했어요.';render();}};const flush=()=>{recover(s);save();};const hide=()=>{cancel();flush();};const visibility=()=>{hide();if(!document.hidden)render();};
  root.addEventListener('click',click);root.addEventListener('pointerdown',down);root.addEventListener('keydown',key);window.addEventListener('pointermove',drag,{passive:false});window.addEventListener('pointerup',up);window.addEventListener('pointercancel',cancel);root.addEventListener('lostpointercapture',cancel);window.addEventListener('blur',cancel);window.addEventListener('pagehide',hide);document.addEventListener('visibilitychange',visibility);
  const timer=window.setInterval(()=>{const before=s.energy;recover(s);if(accelerated&&++ticks%10===0&&s.energy<CAP){s.energy++;s.anchor=Date.now();}if(before!==s.energy)save();updateClock();},1000);save();render();
  return{destroy(){cancel();flush();clearInterval(timer);root.removeEventListener('click',click);root.removeEventListener('pointerdown',down);root.removeEventListener('keydown',key);window.removeEventListener('pointermove',drag);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',cancel);root.removeEventListener('lostpointercapture',cancel);window.removeEventListener('blur',cancel);window.removeEventListener('pagehide',hide);document.removeEventListener('visibilitychange',visibility);root.innerHTML='';}};
}
