// @vitest-environment happy-dom
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {startMergePlacement,KEY} from './merge-placement-prototype';
import {fresh,type State} from './merge-placement-state';
let root:HTMLElement,handle:ReturnType<typeof startMergePlacement>;
const cell=(i:number)=>root.querySelector<HTMLButtonElement>(`[data-cell="${i}"]`)!;const button=(a:string)=>root.querySelector<HTMLButtonElement>(`[data-action="${a}"]`)!;const state=()=>JSON.parse(localStorage.getItem(KEY)!) as State;
function event(target:EventTarget,type:string,x=10,y=10,id=1){target.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:id,isPrimary:true,button:0,clientX:x,clientY:y}));}
beforeEach(()=>{vi.useFakeTimers();window.confirm=vi.fn(()=>true);localStorage.clear();document.body.innerHTML='<div id="game-root"></div>';root=document.getElementById('game-root')!;root.setPointerCapture=vi.fn();root.hasPointerCapture=vi.fn(()=>false);root.releasePointerCapture=vi.fn();handle=startMergePlacement('game-root');});
afterEach(()=>{handle.destroy();vi.restoreAllMocks();vi.useRealTimers();document.body.innerHTML='';});
describe('E v2 scheduled placement interactions',()=>{
 it('shows the next location and opens directly into it with one primary button',()=>{expect(cell(38).classList.contains('next-slot')).toBe(true);expect(root.querySelector('[data-action=pending]')).toBeNull();button('supply').click();expect(state().board[38]).not.toBeNull();expect(state().energy).toBe(29);expect(cell(39).classList.contains('next-slot')).toBe(true);});
 it('keeps undo and return as compact board tools and removes manual install/delivery',()=>{expect(root.querySelector('.placement-mini-actions')).not.toBeNull();expect(button('undo').textContent).toBe('↶');expect(button('return').textContent).toBe('↗');expect(root.querySelector('[data-action=install]')).toBeNull();expect(root.querySelector('[data-action=deliver]')).toBeNull();});
 it('only merges adjacent pairs and blocks empty movement',()=>{const hit=vi.spyOn(document,'elementFromPoint').mockImplementation(()=>cell(41));const before=state().board;event(cell(1),'pointerdown');event(window,'pointermove',60,60);expect(cell(41).classList.contains('drop-invalid')).toBe(true);event(window,'pointerup',60,60);expect(state().board).toEqual(before);hit.mockImplementation(()=>cell(0));event(cell(1),'pointerdown');event(window,'pointermove',60,60);expect(cell(0).classList.contains('drop-merge')).toBe(true);event(window,'pointerup',60,60);expect(state().merges).toBe(1);});
 it('automatically installs and delivers, emitting motion extension events',()=>{const motions:any[]=[];root.addEventListener('dbg:merge-motion',(e)=>motions.push((e as CustomEvent).detail));cell(1).click();cell(0).click();expect(state().installed).toEqual([true,false,true,true]);cell(3).click();cell(2).click();expect(state().order).toBe(1);expect(state().coins).toBe(500);expect(motions.some(e=>e.type==='installed')).toBe(true);expect(motions.some(e=>e.type==='delivered')).toBe(true);expect(root.querySelector('.motion-delivered')).not.toBeNull();});
 it('returns a selected part after confirmation and undoes it',()=>{cell(0).click();const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);button('return').click();expect(state().board[0]).not.toBeNull();confirm.mockReturnValue(true);button('return').click();expect(state().board[0]).toBeNull();button('undo').click();expect(state().board[0]).not.toBeNull();});
 it('full board blocks supply until a return creates the scheduled space',()=>{handle.destroy();const s=fresh();s.board.fill({kind:0,level:1});localStorage.setItem(KEY,JSON.stringify(s));handle=startMergePlacement('game-root');expect(button('supply').disabled).toBe(true);cell(41).click();button('return').click();expect(button('supply').disabled).toBe(false);expect(cell(41).classList.contains('next-slot')).toBe(true);});
 it('keeps legacy save key, remounts progress and tolerates unavailable storage',()=>{button('supply').click();const before=state();handle.destroy();handle=startMergePlacement('game-root');expect(state()).toEqual(before);handle.destroy();vi.spyOn(localStorage,'setItem').mockImplementation(()=>{throw new Error('unavailable');});handle=startMergePlacement('game-root');expect(root.querySelector('[data-save]')?.textContent).toContain('저장 불가');});
});
