import {describe,it,expect,vi} from 'vitest';
import {fresh,supply,nextSlot,drop,canMerge,undo,returnPart,upgrade,restore,recover,RECOVERY} from './merge-placement-state';
describe('E v2 scheduled placement rules',()=>{
 it('preselects the empty cell nearest the intake and uses it on draw',()=>{const s=fresh(0);expect(nextSlot(s)).toBe(38);const result=supply(s,0,()=>.9)!;expect(result.events[0]).toMatchObject({type:'placed',index:38});expect(s.board[38]).toEqual({kind:3,level:1});expect(s.energy).toBe(29);expect(nextSlot(s)).toBe(39);});
 it('does not charge or call rng when the board is full or energy is empty',()=>{const s=fresh(0),rng=vi.fn(()=>0);s.board.fill({kind:0,level:1});expect(supply(s,0,rng)).toBeNull();expect(rng).not.toHaveBeenCalled();s.board[0]=null;s.energy=0;expect(supply(s,0,rng)).toBeNull();expect(rng).not.toHaveBeenCalled();});
 it('merges only horizontal or vertical neighbors into the chosen destination',()=>{const s=fresh(0);const result=drop(s,1,0)!;expect(result.events[0]).toMatchObject({type:'merged',from:1,to:0,part:{kind:0,level:2}});expect(s.board[1]).toBeNull();expect(s.merges).toBe(1);});
 it('rejects distant, diagonal, wrapped, unlike, same-cell and max-level targets',()=>{for(const [from,to,a,b] of [[0,41,1,1],[0,7,1,1],[5,6,1,1],[0,1,4,4],[0,1,1,2],[0,0,1,1]]){const s=fresh();s.board.fill(null);s.board[from]={kind:0,level:a};s.board[to]={kind:0,level:b};const before=structuredClone(s);expect(canMerge(s,from,to)).toBe(false);expect(drop(s,from,to)).toBeNull();expect(s).toEqual(before);}});
 it('automatically installs eligible parts and delivers at most one order per action',()=>{const s=fresh(0);const first=drop(s,1,0)!;expect(first.events.filter(e=>e.type==='installed').map(e=>e.kind)).toEqual([0,2,3]);expect(s.installed).toEqual([true,false,true,true]);const second=drop(s,3,2)!;expect(second.events.at(-1)).toEqual({type:'delivered',reward:500,order:1});expect(s.coins).toBe(500);expect(s.installed).toEqual([false,false,false,false]);expect(second.events.filter(e=>e.type==='delivered')).toHaveLength(1);});
 it('undo reverses merge and automatic progress as one action',()=>{const s=fresh(0);drop(s,1,0);const before=structuredClone(s);drop(s,3,2);expect(s.order).toBe(1);expect(undo(s)).toBe(true);expect({...s,undo:null}).toEqual({...before,undo:null});expect(undo(s)).toBe(false);});
 it('new supply clears old undo and cannot refund energy or reroll',()=>{const s=fresh(0);returnPart(s,0);expect(s.undo).not.toBeNull();supply(s,0,()=>.9);expect(s.undo).toBeNull();expect(s.energy).toBe(29);expect(undo(s)).toBe(false);});
 it('return frees the next scheduled cell and can be undone',()=>{const s=fresh(0);const at=nextSlot(s);s.board[at]={kind:1,level:1};expect(returnPart(s,at)).toBe(true);expect(nextSlot(s)).toBe(at);expect(undo(s)).toBe(true);expect(s.board[at]).not.toBeNull();});
 it('undo after recovery preserves recovered energy and interval',()=>{const s=fresh(0);returnPart(s,0);s.energy=29;s.anchor=0;recover(s,RECOVERY);undo(s);expect(s.energy).toBe(30);expect(s.anchor).toBe(RECOVERY);});
 it('cannot duplicate salary through growth undo',()=>{const s=fresh(0);s.coins=500;expect(upgrade(s)).toBe(true);expect(s.growth).toBe(1);undo(s);expect(s.growth).toBe(0);expect(s.coins).toBe(500);});
 it('migrates v1 pending and held parts into scheduled cells',()=>{const old:any=fresh(0);old.version=1;old.pending={kind:2,level:1};old.held={kind:3,level:2};const migrated=restore(JSON.stringify(old),0);expect(migrated.version).toBe(2);expect(migrated.board[38]).toEqual(old.pending);expect(migrated.board[39]).toEqual(old.held);expect(migrated.undo).toBeNull();});
 it('persists progress and rejects corrupt input or injected history resources',()=>{const s=fresh(0);returnPart(s,0);const restored=restore(JSON.stringify(s),0);expect(restored).toEqual(s);const raw=JSON.parse(JSON.stringify(s));raw.undo.energy=999;raw.undo.anchor=999;const clean=restore(JSON.stringify(raw),0);undo(clean);expect(clean.energy).toBe(30);expect(clean.anchor).toBe(0);raw.board=[];expect(restore(JSON.stringify(raw),0)).toEqual(fresh(0));});
});
