import {describe,it,expect} from 'vitest';
import {fresh,recover,RECOVERY,CAP,mergeGroup,merge,move,supply,install,deliver,restore,upgrade,nextSlot} from './merge-intake-state';
describe('intake D',()=>{
 it('first order completes without energy or randomness and salary cannot duplicate',()=>{const s=fresh(0);expect(merge(s,0)).toBe(true);expect(merge(s,2)).toBe(true);[0,2,4,5].forEach(i=>expect(install(s,i)).toBe(true));expect(deliver(s)).toBe(true);expect(deliver(s)).toBe(false);expect(s.coins).toBe(500);expect(s.energy).toBe(CAP);expect(upgrade(s)).toBe(true);expect(upgrade(s)).toBe(false);});
 it('accepts L shape, rejects diagonal and row wrapping, consumes exactly highlighted triple',()=>{const s=fresh();s.board.fill(null);[0,1,6,7].forEach(i=>s.board[i]={kind:0,level:1});const g=mergeGroup(s,0);expect(g).toHaveLength(3);merge(s,0);expect(s.board[7]).toEqual({kind:0,level:1});expect(s.board[0]?.level).toBe(2);s.board.fill(null);[5,6,11].forEach(i=>s.board[i]={kind:0,level:1});expect(mergeGroup(s,5)).toEqual([]);s.board.fill(null);[0,7,14].forEach(i=>s.board[i]={kind:0,level:1});expect(mergeGroup(s,0)).toEqual([]);});
 it('never merges different levels/kinds or max level',()=>{const s=fresh();s.board[1]={kind:0,level:2};expect(merge(s,0)).toBe(false);s.board[1]={kind:1,level:1};expect(merge(s,0)).toBe(false);[0,1,6].forEach(i=>s.board[i]={kind:0,level:4});expect(merge(s,0)).toBe(false);});
 it('supplies bottom-left first and preserves energy and board when full or empty energy',()=>{const s=fresh(0);expect(nextSlot(s)).toBe(36);expect(supply(s,0,()=>0)).toBe(true);expect(s.board[36]?.kind).toBe(0);expect(s.energy).toBe(29);s.board.fill({kind:0,level:1});expect(supply(s,0)).toBe(false);expect(s.energy).toBe(29);s.board[36]=null;s.energy=0;expect(supply(s,0)).toBe(false);expect(s.board[36]).toBe(null);});
 it('forces an uninstalled kind after four misses',()=>{const s=fresh(0);s.installed=[true,true,true,false];for(let i=0;i<4;i++){const values=[.9,0,0];supply(s,0,()=>values.shift()!);}expect(s.misses).toBe(4);supply(s,0,()=>0);expect(s.misses).toBe(0);expect(s.board[40]?.kind).toBe(3);});
 it('recovers offline preserving partial interval and discards surplus at cap',()=>{const s=fresh(0);s.energy=25;recover(s,RECOVERY*2+500);expect(s.energy).toBe(27);expect(s.anchor).toBe(RECOVERY*2);recover(s,RECOVERY*20);expect(s.energy).toBe(30);supply(s,RECOVERY*20,()=>0);recover(s,RECOVERY*20+500);expect(s.energy).toBe(29);});
 it('restores progress and rejects corrupt data and clock rollback safely',()=>{const s=fresh(0);s.energy=20;expect(restore(JSON.stringify(s),RECOVERY*2).energy).toBe(22);expect(restore('{',100)).toEqual(fresh(100));expect(restore(JSON.stringify({...s,board:[]}),100)).toEqual(fresh(100));s.anchor=1000;recover(s,500);expect(s.energy).toBe(20);expect(s.anchor).toBe(500);});
 it('swaps occupied cells without loss and keeps leftovers after delivery',()=>{const s=fresh();const p=s.board[0],q=s.board[4];expect(move(s,0,4)).toBe(true);expect(s.board[0]).toEqual(q);expect(s.board[4]).toEqual(p);expect(move(s,42,0)).toBe(false);const board=structuredClone(s.board);s.installed.fill(true);deliver(s);expect(s.board).toEqual(board);});
});
