// @vitest-environment happy-dom
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {startMergePlacement,KEY} from './merge-placement-prototype';
import {fresh,type State} from './merge-placement-state';
let root:HTMLElement,handle:ReturnType<typeof startMergePlacement>;
const cell=(i:number)=>root.querySelector<HTMLButtonElement>(`[data-cell="${i}"]`)!;
const button=(action:string)=>root.querySelector<HTMLButtonElement>(`[data-action="${action}"]`)!;
const state=()=>JSON.parse(localStorage.getItem(KEY)!) as State;
function event(target:EventTarget,type:string,x=10,y=10,id=1){target.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:id,isPrimary:true,button:0,clientX:x,clientY:y}));}
beforeEach(()=>{vi.useFakeTimers();window.confirm=vi.fn(()=>true);localStorage.clear();document.body.innerHTML='<div id="game-root"></div>';root=document.getElementById('game-root')!;root.setPointerCapture=vi.fn();root.hasPointerCapture=vi.fn(()=>false);root.releasePointerCapture=vi.fn();handle=startMergePlacement('game-root');});
afterEach(()=>{handle.destroy();vi.restoreAllMocks();vi.useRealTimers();document.body.innerHTML='';});
describe('E placement interactions',()=>{
 it('draws into pending and places by tap, cancel preserves the part, undo restores it',()=>{const before=state().board;button('supply').click();const part=state().pending;expect(part).not.toBeNull();expect(state().board).toEqual(before);expect(button('supply').disabled).toBe(true);button('cancel').click();cell(41).click();expect(state().pending).toEqual(part);button('pending').click();cell(41).click();expect(state().board[41]).toEqual(part);button('undo').click();expect(state().pending).toEqual(part);expect(state().energy).toBe(29);});
 it('shows placement ghost and adjacent-match preview, then commits once',()=>{handle.destroy();const s=fresh();s.pending={kind:0,level:1};localStorage.setItem(KEY,JSON.stringify(s));handle=startMergePlacement('game-root');vi.spyOn(document,'elementFromPoint').mockImplementation(()=>cell(7));event(button('pending'),'pointerdown');event(window,'pointermove',60,60);expect(document.querySelector('.placement-drag-ghost')).not.toBeNull();expect(cell(7).querySelector('[data-preview]')).not.toBeNull();expect(cell(1).classList.contains('preview-match')).toBe(true);event(window,'pointerup',60,60);expect(state().board[7]).toEqual({kind:0,level:1});expect(state().pending).toBeNull();expect(state().merges).toBe(0);});
 it('rejects occupied placement, outside drops, escape and pointer cancellation without loss',()=>{button('supply').click();const before=state();const hit=vi.spyOn(document,'elementFromPoint').mockImplementation(()=>cell(0));event(button('pending'),'pointerdown');event(window,'pointermove',60,60);event(window,'pointerup',60,60);expect(state()).toEqual(before);hit.mockReturnValue(null);event(button('pending'),'pointerdown');event(window,'pointermove',60,60);event(window,'pointerup',60,60);expect(state()).toEqual(before);event(button('pending'),'pointerdown');event(window,'pointermove',60,60);event(window,'pointercancel');expect(document.querySelector('.placement-drag-ghost')).toBeNull();root.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));expect(state()).toEqual(before);});
 it('only merges adjacent pairs, blocking empty movement and distant merge',()=>{const hit=vi.spyOn(document,'elementFromPoint').mockImplementation(()=>cell(41));const before=state().board;event(cell(1),'pointerdown');event(window,'pointermove',60,60);expect(cell(41).classList.contains('drop-invalid')).toBe(true);event(window,'pointerup',60,60);expect(state().board).toEqual(before);hit.mockImplementation(()=>cell(6));event(cell(1),'pointerdown');event(window,'pointermove',60,60);event(window,'pointerup',60,60);expect(state().board).toEqual(before);hit.mockImplementation(()=>cell(0));event(cell(1),'pointerdown');event(window,'pointermove',60,60);expect(cell(0).classList.contains('drop-merge')).toBe(true);event(window,'pointerup',60,60);cell(0).dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));expect(state().merges).toBe(1);expect(state().board[0]?.level).toBe(2);});
 it('holds a pending part, draws another and retains both on remount',()=>{button('supply').click();const first=state().pending;button('hold').click();expect(state().held).toEqual(first);button('supply').click();const second=state().pending;button('hold').click();expect(state().pending).toEqual(first);expect(state().held).toEqual(second);const before=state();handle.destroy();handle=startMergePlacement('game-root');expect(state()).toEqual(before);});
 it('completes bike through taps, then grows and undoes without duplicate rewards',()=>{cell(1).click();cell(0).click();button('install').click();cell(3).click();cell(2).click();button('install').click();cell(4).click();button('install').click();cell(5).click();button('install').click();button('deliver').click();expect(state().coins).toBe(500);button('upgrade').click();expect(state().growth).toBe(1);button('undo').click();expect(state().growth).toBe(0);expect(state().coins).toBe(500);});
 it('full board allows confirmed return and undo but blocks supply',()=>{handle.destroy();const s=fresh();s.board.fill({kind:0,level:1});localStorage.setItem(KEY,JSON.stringify(s));handle=startMergePlacement('game-root');expect(button('supply').disabled).toBe(true);cell(41).click();const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);button('return').click();expect(state().board[41]).not.toBeNull();confirm.mockReturnValue(true);button('return').click();expect(state().board[41]).toBeNull();expect(button('supply').disabled).toBe(false);button('undo').click();expect(state().board[41]).not.toBeNull();});
 it('keeps drag intact while energy recovers and cleans up on exit',()=>{button('supply').click();vi.spyOn(document,'elementFromPoint').mockImplementation(()=>cell(41));event(button('pending'),'pointerdown');event(window,'pointermove',60,60);vi.advanceTimersByTime(600_000);expect(document.querySelector('.placement-drag-ghost')).not.toBeNull();event(window,'pointerup',60,60);expect(state().energy).toBe(30);expect(state().board[41]).not.toBeNull();handle.destroy();expect(vi.getTimerCount()).toBe(0);expect(root.childElementCount).toBe(0);});
 it('keeps D save untouched and tolerates unavailable storage',()=>{localStorage.setItem('dbg-lab-merge-intake-v1','D save');button('supply').click();expect(localStorage.getItem('dbg-lab-merge-intake-v1')).toBe('D save');handle.destroy();vi.spyOn(localStorage,'setItem').mockImplementation(()=>{throw new Error('unavailable');});handle=startMergePlacement('game-root');expect(root.querySelector('[data-save]')?.textContent).toContain('저장 불가');});
});
