import {describe,it,expect} from 'vitest';
import {fresh,recover,RECOVERY,CAP,canMerge,drop,supply,install,deliver,restore,upgrade,nextSlot} from './merge-intake-state';
describe('intake D overlap v2',()=>{
 it('first order completes without waiting and salary cannot duplicate',()=>{const s=fresh(0);expect(drop(s,1,0)).toBe('merged');expect(drop(s,3,2)).toBe('merged');[0,2,4,5].forEach(i=>expect(install(s,i)).toBe(true));expect(deliver(s)).toBe(true);expect(deliver(s)).toBe(false);expect(s.coins).toBe(500);expect(s.energy).toBe(CAP);expect(upgrade(s)).toBe(true);expect(upgrade(s)).toBe(false);});
 it('merges distant matching pairs at destination, consuming only two and no energy',()=>{const s=fresh(0);s.board.fill(null);[0,20,41].forEach(i=>s.board[i]={kind:0,level:1});expect(canMerge(s,0,41)).toBe(true);expect(drop(s,0,41)).toBe('merged');expect(s.board[0]).toBe(null);expect(s.board[41]).toEqual({kind:0,level:2});expect(s.board[20]).toEqual({kind:0,level:1});expect(s.merges).toBe(1);expect(s.energy).toBe(30);});
 it('different kinds, levels and maximum-level parts swap instead of being lost',()=>{for(const p of [{kind:1,level:1},{kind:0,level:2},{kind:0,level:4}]){const s=fresh();s.board[0]={kind:0,level:p.level===4?4:1};s.board[41]=p;const before=structuredClone(s.board);expect(canMerge(s,0,41)).toBe(false);expect(drop(s,0,41)).toBe('swapped');expect(s.board[0]).toEqual(before[41]);expect(s.board[41]).toEqual(before[0]);expect(s.merges).toBe(0);}});
 it('same-cell, empty-source and off-board releases have no effects',()=>{const s=fresh();const before=structuredClone(s);for(const [a,b] of [[0,0],[0,-1],[0,42],[42,0],[20,0],[0,1.2]])expect(drop(s,a,b)).toBe('none');expect(s).toEqual(before);});
 it('never automatically merges when a part is placed adjacent',()=>{const s=fresh();expect(drop(s,6,7)).toBe('moved');expect(s.board[7]?.level).toBe(1);expect(s.merges).toBe(0);});
 it('fills nearest tray cells deterministically, reuses closer gaps and rejects full/zero energy supply',()=>{const s=fresh(0);expect(nextSlot(s)).toBe(38);expect(supply(s,0,()=>0)).toBe(true);expect(s.board[38]?.kind).toBe(0);expect(nextSlot(s)).toBe(39);supply(s,0,()=>0);expect(nextSlot(s)).toBe(37);s.board[38]=null;expect(nextSlot(s)).toBe(38);s.board.fill({kind:0,level:1});const energy=s.energy;expect(supply(s,0)).toBe(false);expect(s.energy).toBe(energy);s.board[38]=null;s.energy=0;expect(supply(s,0)).toBe(false);expect(s.board[38]).toBe(null);});
 it('forces an uninstalled kind after four misses',()=>{const s=fresh(0);s.installed=[true,true,true,false];for(let i=0;i<4;i++){const values=[.9,0,0];supply(s,0,()=>values.shift()!);}expect(s.misses).toBe(4);const slot=nextSlot(s);supply(s,0,()=>0);expect(s.misses).toBe(0);expect(s.board[slot]?.kind).toBe(3);});
 it('recovers offline preserving partial interval and discards surplus at cap',()=>{const s=fresh(0);s.energy=25;recover(s,RECOVERY*2+500);expect(s.energy).toBe(27);expect(s.anchor).toBe(RECOVERY*2);recover(s,RECOVERY*20);expect(s.energy).toBe(30);supply(s,RECOVERY*20,()=>0);recover(s,RECOVERY*20+500);expect(s.energy).toBe(29);});
 it('preserves v1 board, salary, growth, order and installed parts on upgrade',()=>{const s=fresh(0);s.order=4;s.coins=1000;s.growth=2;s.installed[2]=true;s.board[41]={kind:2,level:4};expect(restore(JSON.stringify(s),0)).toEqual(s);});
 it('rejects corrupt saves and handles clock rollback safely',()=>{const s=fresh(0);s.energy=20;expect(restore(JSON.stringify(s),RECOVERY*2).energy).toBe(22);expect(restore('{',100)).toEqual(fresh(100));expect(restore(JSON.stringify({...s,board:[]}),100)).toEqual(fresh(100));s.anchor=1000;recover(s,500);expect(s.energy).toBe(20);expect(s.anchor).toBe(500);});
 it('retains leftover parts after delivering and advances repeated orders',()=>{const s=fresh();const board=structuredClone(s.board);s.installed.fill(true);deliver(s);expect(s.board).toEqual(board);expect(s.order).toBe(1);});
});
