import {describe,it,expect,vi} from 'vitest';
import {fresh,supply,place,hold,drop,canMerge,undo,returnPart,install,deliver,upgrade,restore,recover,RECOVERY,placementMatches} from './merge-placement-state';
describe('E fixed placement rules',()=>{
 it('creates one pending part without changing the board; blocks another draw',()=>{const s=fresh(0), board=structuredClone(s.board), rng=vi.fn(()=>0);expect(supply(s,0,rng)).toBe(true);expect(s.board).toEqual(board);expect(s.pending).toEqual({kind:0,level:2});expect(s.energy).toBe(29);const calls=rng.mock.calls.length;expect(supply(s,0,rng)).toBe(false);expect(rng).toHaveBeenCalledTimes(calls);expect(s.energy).toBe(29);});
 it('places only into valid empty cells, without auto merge or additional charge',()=>{const s=fresh(0);s.pending={kind:0,level:1};for(const i of [-1,42,1.5,0])expect(place(s,i)).toBe(false);expect(placementMatches(s,7)).toEqual([1,6]);expect(place(s,7)).toBe(true);expect(s.pending).toBeNull();expect(s.board[7]).toEqual({kind:0,level:1});expect(s.merges).toBe(0);expect(s.energy).toBe(30);});
 it('merges horizontal/vertical neighbors into the chosen destination with no chain',()=>{for(const [from,to] of [[1,0],[0,6]]){const s=fresh(0);expect(drop(s,from,to)).toBe('merged');expect(s.board[from]).toBeNull();expect(s.board[to]).toEqual({kind:0,level:2});expect(s.merges).toBe(1);expect(s.energy).toBe(30);}});
 it('rejects distant, diagonal, wrapped, empty, unlike, same-cell and max-level targets',()=>{for(const [from,to,a,b] of [[0,41,1,1],[0,7,1,1],[5,6,1,1],[0,1,4,4],[0,1,1,2],[0,0,1,1]]){const s=fresh();s.board.fill(null);s.board[from]={kind:0,level:a};s.board[to]={kind:0,level:b};const before=structuredClone(s);expect(canMerge(s,from,to)).toBe(false);expect(drop(s,from,to)).toBe('none');expect(s).toEqual(before);}const s=fresh(),before=structuredClone(s);for(const [a,b] of [[0,20],[0,2],[0,-1],[42,0],[0,1.2]])expect(drop(s,a,b)).toBe('none');expect(s).toEqual(before);});
 it('holds, swaps and retrieves one part without creating or losing parts',()=>{const s=fresh();s.pending={kind:0,level:1};hold(s);expect(s.held).toEqual({kind:0,level:1});expect(s.pending).toBeNull();s.pending={kind:1,level:2};hold(s);expect(s.pending).toEqual({kind:0,level:1});expect(s.held).toEqual({kind:1,level:2});place(s,41);hold(s);expect(s.pending).toEqual({kind:1,level:2});expect(s.held).toBeNull();});
 it('undo restores drawn identity and cannot refund energy or reroll supply',()=>{const s=fresh(0);supply(s,0,()=>0);const part=structuredClone(s.pending);expect(undo(s)).toBe(false);place(s,41);expect(undo(s)).toBe(true);expect(s.pending).toEqual(part);expect(s.energy).toBe(29);expect(s.supplied).toBe(1);expect(undo(s)).toBe(false);expect(supply(s,0)).toBe(false);place(s,41);supply(s,0,()=>.9);expect(undo(s)).toBe(false);});
 it('undo after recovery preserves the recovered energy and interval',()=>{const s=fresh(0);supply(s,0,()=>0);place(s,41);recover(s,RECOVERY);undo(s);expect(s.energy).toBe(30);expect(s.anchor).toBe(RECOVERY);});
 it('full board blocks charges and is recoverable by returning a part',()=>{const s=fresh(0);s.board.fill({kind:0,level:1});expect(supply(s,0)).toBe(false);expect(s.energy).toBe(30);expect(returnPart(s,41)).toBe(true);expect(s.returned).toBe(1);expect(supply(s,0,()=>0)).toBe(true);expect(place(s,41)).toBe(true);});
 it('undo restores merge, hold and return exactly once',()=>{for(const action of [(s:ReturnType<typeof fresh>)=>drop(s,0,1),(s:ReturnType<typeof fresh>)=>returnPart(s,0),(s:ReturnType<typeof fresh>)=>hold(s)]){const s=fresh(0);s.pending={kind:2,level:1};const before=structuredClone(s);action(s);expect(undo(s)).toBe(true);expect(s).toEqual(before);}});
 it('completes first bike, and undo cannot duplicate salary or growth',()=>{const s=fresh(0);drop(s,1,0);drop(s,3,2);[0,2,4,5].forEach(i=>expect(install(s,i)).toBe(true));deliver(s);expect(s.coins).toBe(500);expect(deliver(s)).toBe(false);undo(s);expect(s.coins).toBe(0);expect(s.installed.every(Boolean)).toBe(true);deliver(s);upgrade(s);expect(s.growth).toBe(1);undo(s);expect(s.coins).toBe(500);expect(s.growth).toBe(0);expect(undo(s)).toBe(false);});
 it('persists pending, held, undo and partial offline recovery',()=>{const s=fresh(0);supply(s,0,()=>0);hold(s);supply(s,0,()=>.9);place(s,41);const restored=restore(JSON.stringify(s),RECOVERY+123);expect(restored.energy).toBe(29);expect(restored.anchor).toBe(RECOVERY);expect(restored.held).toEqual(s.held);expect(undo(restored)).toBe(true);expect(restored.pending).toEqual({kind:3,level:1});expect(restored.board[41]).toBeNull();});
 it('rejects corrupt progress, drops malformed history and excludes injected resource fields',()=>{const s=fresh(0);expect(restore('{',0)).toEqual(s);expect(restore(JSON.stringify({...s,pending:{kind:9,level:1}}),0)).toEqual(s);drop(s,0,1);const raw=JSON.parse(JSON.stringify(s));raw.undo.energy=999;raw.undo.anchor=999;const restored=restore(JSON.stringify(raw),0);undo(restored);expect(restored.energy).toBe(30);expect(restored.anchor).toBe(0);raw.undo.board=[];expect(restore(JSON.stringify(raw),0).undo).toBeNull();});
 it('zero energy does not prevent using already received or held parts',()=>{const s=fresh(0);s.energy=0;s.pending={kind:2,level:1};expect(place(s,41)).toBe(true);expect(supply(s,0)).toBe(false);expect(s.energy).toBe(0);});
});
